<?php
/*
* Autostore autos Theme html topmenu template.
*
*@author Hrytsuk Walentun vgritsukm@gmail.com
*@copyright 2020 zevsi
*/

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation" data-action="navigation">
    <div class="all-categories-block">
        <span class="all-categories">All Categories</span>
        <span class="menu-burgers-icon"></span>
        <ul class="menu-ul"  data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?= /* @noEscape */ $_menuHtml?>
        </ul>
    </div>
    <div class="child-navigation">
        <span class="burger-menu-right">
            Menu
            <span></span>
        </span>
        <?= $block->getChildHtml() ?>
    </div>
</nav>
