<?php
/*
* Autostore autos Store switch languages template.
*
*@author Hrytsuk Walentun vgritsukm@gmail.com
*@copyright 2020 zevsi
*/


/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores()) > 1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <li class="switcher language switcher-language" data-ui-id="language-switcher"
        id="switcher-language<?= $block->escapeHtmlAttr($id); ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')); ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $block->escapeHtmlAttr($id); ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()); ?>">
                    <span><?= $block->escapeHtml($block->getStoreName()); ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown"
                data-target="dropdown">
                <?php foreach ($block->getStores() as $lang) : ?>
                    <?php if ($lang->getId() != $block->getCurrentStoreId()) : ?>
                        <li class="view-<?= $block->escapeHtml($lang->getCode()); ?> switcher-option">
                            <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($lang)); ?>">
                                <?= $block->escapeHtml($lang->getName()); ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </li>
<?php endif; ?>
