<?php
/**
 * AutoStore default Catalog product custom-tab template
 *
 * @author Yuri Chlek yurichhlek@gmail.com
 * @copyright 2020 Chlek
 */
?>

<div class="product custom-tab">
    <p class="value-custom-tab" id="custom-tab">
       <?=__("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
        magna aliqua. Duis auto mr reprehenderit in voluptateveli esse cillum dolore eu fugiat nulla pariatur. Ut enim
        ad minim veniam, quis nostrud exercitation ullamc laboris nisi ut aliquip ex eacommod consequat. Duis
        reprehenderit iesse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non"); ?>
    </p>
    <iframe height="315" src="https://www.youtube.com/embed/BW6LuHPDNAY" frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
