<?php
/**
 * Editorial default Cms parentTemplate template
 * @author Nikolaichuk Oleksandr nikolaychuk.alexander@gmail.com
 * @copyright 2020 Nikolaichuk
 */
$title = $block->hasData('header') ? $block->getData('header') : '';
?>
<div class="editorial-wrapper">
    <div class="editorial__title">
        <?=$title?>
    </div>
    <div class="editorial__content">
        <div class="editorial__content__left-container editorial__column">
            <div class="editorial__content__card">
                <?=$block->getChildHtml('editorial.child1')?>
            </div>
            <div class="editorial__content__card">
                <?=$block->getChildHtml('editorial.child2')?>
            </div>
            <div class="editorial__content__card">
                <?=$block->getChildHtml('editorial.child3')?>
            </div>
            <div class="editorial__content__card">
                <?=$block->getChildHtml('editorial.child4')?>
            </div>
        </div>
        <div class="editorial__content__right-container editorial__column">
            <div class="editorial__content__card">
                <?=$block->getChildHtml('editorial.child5')?>
            </div>
        </div>
    </div>
</div>
