<?php
/*
*HrytsukWM Monnier monnierTopic Cms home-page home template.
*
*@author Hrytsuk Walentun vgritsukm@gmail.com
*@copyright 2020 zevsi
*/
?>

<div class="wrappers">
    <h2 class="title-page"><?= $block->hasData('editorial') ? $block->getData('editorial') : "" ?></h2>
    <div class="wrapper-edit">
        <div class="cart-wrapper">
            <?= $block->getChildHtml("home-shild1") ?>
            <?= $block->getChildHtml("home-shild2") ?>
            <?= $block->getChildHtml("home-shild3") ?>
            <?= $block->getChildHtml("home-shild4") ?>
        </div>
        <div class="hero-product">
            <?= $block->getChildHtml("home-shild5") ?>
        </div>
    </div>
</div>

