<?php
/*
*Monnier default title home page.
*
*@author vlromaniuk  vlad96r@protonmail.com
*@copyright 2020 vlromaniuk
* */
?>
<?= __('EDITORIAL')?>
<div>
    <?= $block->getChildHtml('editorial.child.1') ?>
    <?= $block->getChildHtml('editorial.child.2') ?>
    <?= $block->getChildHtml('editorial.child.3') ?>
    <?= $block->getChildHtml('editorial.child.4') ?>
    <?= $block->getChildHtml('editorial.child.5') ?>
</div>
