<?php
/**
 * AutoStore default LayeredNavigation layer price slider template
 *
 * @author Nikolaichuk Oleksandr nikolaychuk.alexander@gmail.com
 * @copyright 2020 Nikolaichuk
 */
?>
<div class="price-slider__slider" data-mage-init='{"priceRange":{}}'>
    <div id="slider-range"></div>
    <div class="price-slider__controls">
        <span>$</span>
        <input type="number" min="0" id="price-min" class="price-slider__controls__input price-min"/>
        <span>-$</span>
        <input type="number" id="price-max" class="price-slider__controls__input price-max"/>
    </div>
</div>
