<?php
/**
 * AutoStore default Theme product html copyright template
 *
 * @author Yuri Chlek yurichhlek@gmail.com
 * @copyright 2020 Chlek
 */
?>

<div class="bottom-section">
    <div class="wrapper">
        <div class="footer-bottom-section">
            <div class="pay-cards">
                <img src="<?= $block->getViewFileUrl('images/payment-footer.png'); ?>" alt="payment">
            </div>
            <small class="copyright">
                <span><?= __("SM Autostore © 2019 Demo Store. All Rights Reserved. Designed by MagenTech.Com"); ?></span>
            </small>
        </div>
    </div>
</div>
