<?php
/**
 * AutoStore default Theme html copyright template
 *
 * @author Nikolaichuk Oleksandr nikolaychuk.alexander@gmail.com
 * @copyright 2020 Nikolaichuk
 */
?>
<div class="copyright">
    <div class="copyright-wrapper">
        <div class="payment-container">
            <ul class="payment-list">
                <li>
                    <a href="#" class="link maestro">&nbsp;</a>
                </li>
                <li>
                    <a href="#" class="link paypal">&nbsp;</a>
                </li>
                <li>
                    <a href="#" class="link union">&nbsp;</a>
                </li>
                <li>
                    <a href="#" class="link visa">&nbsp;</a>
                </li>
                <li>
                    <a href="#" class="link cirrus">&nbsp;</a>
                </li>
                <li>
                    <a href="#" class="link ebay">&nbsp;</a>
                </li>
            </ul>
        </div>
        <div class="copyright-container">
            <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
            <a href="#" class="link">Designed by MagenTech.Com</a>
        </div>
    </div>
</div>
