<?php
/**
 *autoSTore default Theme templates html topmenu.
 *@author Vladislav Romaniuk vlad96r@protonmial.com
 *@copyright 2020 Vlromaniuk
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation" data-action="navigation">
    <div class="hover-menu">
        <p>All Categories</p>
        <img src="<?= $this->getViewFileUrl('images/menu.png') ?>" alt="">
    </div>
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>

<ul>
    <li>home</li>
    <li>deals</li>
    <li>under$100</li>
    <li>new arrivals</li>
    <li>blog</li>
    <li>about us</li>
    <li>contact us</li>
</ul>
