<?php
/*
*Monnier default editorial parent template.
*
*@author vlromaniuk  vlad96r@protonmail.com
*@copyright 2020 vlromaniuk
* */
?>
<?php
//variables
$block1 = $block->getChildHtml('editorial.child.1');
$block2 = $block->getChildHtml('editorial.child.2');
$block3 = $block->getChildHtml('editorial.child.3');
$block4 = $block->getChildHtml('editorial.child.4');
$block5 = $block->getChildHtml('editorial.child.5');
$titlePage = $block->hasData('title.page') ? ($block->getData('title.page')) : '';
?>
<h2 class="page-titles"><?= $titlePage ?></h2>
<div class="cart-wrapper">
    <div class="cart-wrapper-left">
        <?= $block1 ?>
        <?= $block2 ?>
        <?= $block4 ?>
        <?= $block5 ?>
    </div>
    <div class="cart-wrapper-right">
        <?= $block3 ?>
    </div>
</div>
