<?php
/*
*Monnier default editorial child template.
*
*@author vlromaniuk  vlad96r@protonmail.com
*@copyright 2020 vlromaniuk
* */
?>
<?php
//variables
$blockImg = $block->hasData('block.img') ? $block->getData('block.img') : "";
$topDescription = $block->hasData('top.description') ? $block->getData('top.description') : '';
$titleCard = $block->hasData('title.card') ? $block->getData('title.card') : '';
$bottomDescription = $block->hasData('bottom.description') ? $block->getData('bottom.description') : '';
$cardUrl = $block->hasData('card.url') ? ($block->getData('card.url')) : '';
$textUrl = $block->hasData('text.url') ? ($block->getData('text.url')) : '';
$heroProductValid = $block->hasData('hero.product') ? ($block->getData('hero.product')) : '';
$heroProduct = '<p class="heroProduct">'.$heroProductValid.'</p>';
?>
<div class="card">
    <div class="blockImg"">
        <a href="<?= $cardUrl ?>">
        <?php if ($blockImg) : ?>
            <img src="<?= $block->getViewFileUrl('images/' . $blockImg); ?>"  alt="<?= $topDescription ?>">
        <?php endif;?>
        </a>
        <?=$heroProduct?>
    </div>
    <div class="description">
        <p><?=$topDescription?></p>
        <a class="title-card" href="<?= $cardUrl ?>"><?=$titleCard?></a>
        <p class="bottom-description"><?= $bottomDescription?></p>
        <a class="card-link" href="<?= $cardUrl ?>"><?=$textUrl?></a>
    </div>
</div>

