<?php
/*
 *HrytsukLess lessTopic LayeredNavigation layer filter_price_slider template.
 *
 *@author Hrytsuk Walentun vgritsukm@gmail.com
 *@copyright 2020 zevsi
 */
?>

<div class="slider-range-price" data-mage-init='{"sliderUiPrice":{}}'>
    <a href="http://magento2.local/women/tops-women.html?price=10-20" class="filterHref">
        <span id="amount">10</span>
        <span id="amount2">20</span>
    </a>
    <div id="slider-range" ></div>
</div>
