<div id="my-collapsible" data-mage-init='{"collapsible": {"animate": 1000,"easing":"easeOutCubic"}, "saveState": true}'>
    <div data-role="title">
        <h2>title <button data-role="trigger">go</button></h2>
    </div>
    <div data-role="content" id="example">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi error laborum magni placeat rem. Alias beatae consectetur nam natus obcaecati perspiciatis reiciendis tempora? Accusamus aperiam consequatur esse illum iusto, quia.
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi error laborum magni placeat rem. Alias beatae consectetur nam natus obcaecati perspiciatis reiciendis tempora? Accusamus aperiam consequatur esse illum iusto, quia.
    </div>
</div>
