<?php
/*
 * Vlromaniuk. Learn Templates
 *
 *@author vlromaniuk  vlad96r@protonmail.com
 *@copyright 2020 vlromaniuk
 * */
?>

<?php
/* variables */
$link = $block->hasData('hasLink') ? ($block->getData('hasLink')) : '';
$img = $block->hasData('hasImg') ? $block->getData('hasImg') : "";
$imgAlt = $block->hasData('hasImgAlt') ? $block->getData('hasImgAlt') : "";
$textTranslate = $block->hasData('translate') ? $block->getData('translate') : '';
?>

<?= __("Some Text")?>
<?= $block->getChildHtml('new.template') ?>
<?= $block->hasData('translate') ? $block->getData('translate') : '' ?>
<?php if ($block->hasData('hasBool') && ($block->getData('hasBool'))) : ?>
    <h2><?= __('is True') ?></h2>
<?php endif;?>

<?php if ($link) : ?>
    <a href="<?= $link ?>"><?=__("Link")?></a>
<?php endif;?>
<br>
<?php if ($img) : ?>
    <img src="<?= $block->getViewFileUrl('images/' . $img); ?>" alt="<?= $imgAlt ?>">
<?php endif;?>
